apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: {{ .Values.grafana.serviceType }}
  ports:
    - name: web
      port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
